version: '3.7'
services:
  postgres-service:
    image: postgres:12.2@sha256:c52d4eac43883c53113cee0ebd1ce0fe53ef0604708822901ecca6655968fa9a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  keycloak-service:
    image: jboss/keycloak:10.0.2@sha256:6de74f3624a7408ccc6d8f243f8ee1dc63288088cef42cb7389d89edf6ca7a74
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres-service
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_DATABASE=keycloak
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
    ports:
      - '8090:8080'
    depends_on:
      - postgres-service